version: "3.8"

services:
  minecraft:
    build: .
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      MEMORY: "20G"
      ENABLE_RCON: "true"
      RCON_PORT: "25575"
      RCON_PASSWORD: "Rcon123"
      OPS: "${OPS}"
    volumes:
      - datasrc:/data
    restart: unless-stopped
    entrypoint: ["/start-minecraft.sh"]

volumes:
  datasrc:

